#pragma once

#include <cstdint>
#include <optional>
#include <memory>
#include <limits>
#include <functional>
#include <numeric>
#include <string>
#include <sstream>
#include <boost/enable_shared_from_this.hpp>
#include <vector>
#include <map>
#include <stdexcept>
#include <iostream>
#include <boost/uuid/uuid.hpp> 
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>  
#include <SFML/Graphics.hpp>